name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build with Gradle
        uses: msfjarvis/setup-android@0.1
        with:
          gradleTasks: build
